Repository The-Dark-Nights/back-end, pull requests merged in 2023-08, with the labels that each got.

#9 [Closes #2] Feat : Configuration 패키지 설정
  .github/workflows/gradle-publish.yml
  build.gradle
  src/main/java/com/darknights/devigation/common/annotation/DomainService.java
  src/main/java/com/darknights/devigation/common/annotation/InfraService.java
  src/main/java/com/darknights/devigation/configuration/DatabaseConfiguration.java
  src/main/java/com/darknights/devigation/configuration/WebConfiguration.java
  src/main/resources/application.properties
  src/main/resources/config/mybatis-config.xml
  src/main/resources/mapper/mapper.md
Labels: ✨ Feature, ⚙ Setting

#13 [Closes #3] Feat : 맴버 command, query 엔티티 생성
  src/main/java/com/darknights/devigation/member/command/domain/aggregate/entity/Member.java
  src/main/java/com/darknights/devigation/member/command/domain/aggregate/entity/enumType/PlatformEnum.java
  src/main/java/com/darknights/devigation/member/command/domain/aggregate/entity/enumType/Role.java
  src/main/java/com/darknights/devigation/member/query/domain/aggregate/entity/QueryMember.java
  src/main/java/com/darknights/devigation/member/query/domain/aggregate/entity/enumType/PlatformEnum.java
  src/main/java/com/darknights/devigation/member/query/domain/aggregate/entity/enumType/Role.java
Labels: ✨ Feature

#15 [Closes #14] 게시글 Entity 생성
  src/main/java/com/darknights/devigation/post/command/domain/aggregate/entity/Post.java
  src/main/java/com/darknights/devigation/post/command/domain/aggregate/vo/MemberVO.java
  src/main/java/com/darknights/devigation/post/query/domain/entity/QueryPost.java
Labels: ✨ Feature

#11 [Closes #10]category context entity 작성
  src/main/java/com/darknights/devigation/category/command/domain/aggregate/entity/Category.java
  src/main/java/com/darknights/devigation/category/command/domain/aggregate/vo/MemberVO.java
  src/main/java/com/darknights/devigation/category/query/domain/aggregate/entity/QueryCategory.java
  src/main/java/com/darknights/devigation/category/query/domain/aggregate/vo/MemberVO.java
Labels: ✨ Feature

#18 [Closes #12] roadmap context entity 작성
  src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/entity/Roadmap.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/entity/RoadmapCategory.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/vo/ChildCategoryVO.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/vo/MemberVO.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/vo/ParentCategoryVO.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/vo/RoadmapVO.java
  src/main/java/com/darknights/devigation/roadmap/query/domain/aggregate/entity/QueryRoadmap.java
  src/main/java/com/darknights/devigation/roadmap/query/domain/aggregate/entity/QueryRoadmapCategory.java
  src/main/java/com/darknights/devigation/roadmap/query/domain/aggregate/vo/ChildCategoryVO.java
  src/main/java/com/darknights/devigation/roadmap/query/domain/aggregate/vo/MemberVO.java
  src/main/java/com/darknights/devigation/roadmap/query/domain/aggregate/vo/ParentCategoryVO.java
  src/main/java/com/darknights/devigation/roadmap/query/domain/aggregate/vo/RoadmapVO.java
Labels: ✨ Feature

#21 [#4, #5] Feat : 맴버 mapper, repository 인터페이스 생성
  src/main/java/com/darknights/devigation/member/command/domain/repository/MemberRepository.java
  src/main/java/com/darknights/devigation/member/query/domain/repository/MemberMapper.java
  src/main/java/com/darknights/devigation/member/query/domain/repository/MemberQueryRepository.java
  src/main/resources/mapper/member/MemberMapper.xml
Labels: ✨ Feature

#22 [Closes #20] Feat : category context Create, Update, Delete 기능 작성, Test : category Context CUD test작성
  src/main/java/com/darknights/devigation/category/command/application/dto/CreateCategoryDTO.java
  src/main/java/com/darknights/devigation/category/command/application/dto/UpdateCategoryDTO.java
  src/main/java/com/darknights/devigation/category/command/application/service/CreateCategoryService.java
  src/main/java/com/darknights/devigation/category/command/application/service/DeleteCategoryService.java
  src/main/java/com/darknights/devigation/category/command/application/service/UpdateCategoryService.java
  src/main/java/com/darknights/devigation/category/command/domain/aggregate/entity/Category.java
  src/main/java/com/darknights/devigation/category/command/domain/repository/CategoryRepository.java
  src/main/java/com/darknights/devigation/category/command/domain/service/CategoryService.java
  src/test/java/com/darknights/devigation/category/service/CategoryServiceTests.java
Labels: ✨ Feature, ✅ Test

#23 [Closes #4] Feat : Create Application Service 클래스 생성
  src/main/java/com/darknights/devigation/member/command/application/dto/CreateMemberDTO.java
  src/main/java/com/darknights/devigation/member/command/application/service/CreateMemberService.java
  src/main/java/com/darknights/devigation/member/command/domain/aggregate/entity/Member.java
  src/main/resources/mapper/member/MemberMapper.xml
  src/test/java/com/darknights/devigation/member/command/application/service/CreateMemberServiceTest.java
Labels: ✨ Feature, ✅ Test

#31 Update README.md
  README.md
Labels: 🥰 Accessibility

#33 [Closes #17] 사진 Entity 생성
  src/main/java/com/darknights/devigation/photo/command/domain/aggregate/entity/Photo.java
  src/main/java/com/darknights/devigation/photo/command/domain/aggregate/entity/enumtype/PhotoCategory.java
Labels: ✨ Feature

#35 [Closes #27] Feat : roadmap context Create, Update, Delete 기능 작성, Test : roadmap Context CUD test작성
  src/main/java/com/darknights/devigation/DevigationApplication.java
  src/main/java/com/darknights/devigation/category/command/domain/service/CategoryService.java
  src/main/java/com/darknights/devigation/roadmap/command/application/dto/CreateRoadmapDTO.java
  src/main/java/com/darknights/devigation/roadmap/command/application/dto/UpdateRoadmapDTO.java
  src/main/java/com/darknights/devigation/roadmap/command/application/service/CreateRoadmapService.java
  src/main/java/com/darknights/devigation/roadmap/command/application/service/DeleteRoadmapService.java
  src/main/java/com/darknights/devigation/roadmap/command/application/service/UpdateRoadmapService.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/RoadmapRepository/RoadmapRepository.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/entity/Roadmap.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/entity/RoadmapCategory.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/service/RoadmapService.java
  src/main/java/com/darknights/devigation/roadmap/query/domain/aggregate/entity/QueryRoadmapCategory.java
  src/test/java/com/darknights/devigation/roadmap/service/RoadmapServiceTests.java
Labels: ✨ Feature, ✅ Test

#43 [Closes #42] Feature : JWT 토큰 유효성 검사 후 에러 코드 응답
  src/main/java/com/darknights/devigation/DevigationApplication.java
  src/main/java/com/darknights/devigation/common/filter/JwtExceptionFilter.java
  src/main/java/com/darknights/devigation/common/filter/TokenAuthenticationFilter.java
  src/main/java/com/darknights/devigation/configuration/SecurityConfiguration.java
  src/main/java/com/darknights/devigation/security/command/application/service/CustomTokenService.java
  src/main/java/com/darknights/devigation/security/command/application/service/RestAuthenticationEntryPoint.java
Labels: 📬 API, ✨ Feature

#47 [UPDATE][README] README 2주차 todo 반영
  README.md
Labels: 📃 Docs

#54 [Closes #28] Feat : category context Update 기능 작동 방식 수정, Test : 수정한 category Context update test작성
  src/main/java/com/darknights/devigation/category/command/application/service/UpdateCategoryService.java
  src/test/java/com/darknights/devigation/category/service/CategoryServiceTests.java
Labels: ✨ Feature, ☎️ Request, ✅ Test

#56 [#48] Feature : spring security 401, 403 에러 코드 작성
  src/main/java/com/darknights/devigation/admin/command/application/AdminController.java
  src/main/java/com/darknights/devigation/common/filter/AuthenticationExceptionFilter.java
  src/main/java/com/darknights/devigation/common/filter/TokenAuthenticationFilter.java
  src/main/java/com/darknights/devigation/common/handler/CustomAccessDeniedHandler.java
  src/main/java/com/darknights/devigation/configuration/SecurityConfiguration.java
  src/main/java/com/darknights/devigation/member/query/application/service/FindMemberService.java
  src/main/java/com/darknights/devigation/security/command/application/service/CustomTokenService.java
  src/main/java/com/darknights/devigation/security/command/application/service/CustomUserDetailService.java
  src/main/java/com/darknights/devigation/security/command/domain/exception/ResourceNotFoundException.java
  src/main/java/com/darknights/devigation/security/command/domain/exception/UserNotFoundException.java
Labels: 📬 API, ✨ Feature

#50 [#32] 사진 추가 기능 구현
  src/main/java/com/darknights/devigation/photo/command/application/dto/PhotoDTO.java
  src/main/java/com/darknights/devigation/photo/command/application/service/DeletePhotoService.java
  src/main/java/com/darknights/devigation/photo/command/application/service/InsertPhotoService.java
  src/main/java/com/darknights/devigation/photo/command/application/service/UpdatePhotoService.java
  src/main/java/com/darknights/devigation/photo/command/domain/aggregate/entity/Photo.java
  src/main/java/com/darknights/devigation/photo/command/domain/repository/PhotoRepository.java
  src/main/java/com/darknights/devigation/post/command/application/dto/UpdatePostDTO.java
  src/test/java/com/darknights/devigation/photo/command/service/PhotoServiceTests.java
Labels: ✨ Feature, ✅ Test

#59 [#57, #58] Feature : Response Class 구현 및 통합 예외 처리 구현
  src/main/java/com/darknights/devigation/common/advice/AuthControllerAdvice.java
  src/main/java/com/darknights/devigation/common/entity/api/ApiResponse.java
  src/main/java/com/darknights/devigation/common/entity/error/ErrorResponse.java
  src/main/java/com/darknights/devigation/common/entity/error/ErrorResponseBody.java
  src/main/java/com/darknights/devigation/common/filter/AuthenticationExceptionFilter.java
  src/main/java/com/darknights/devigation/common/handler/CustomAccessDeniedHandler.java
  src/main/java/com/darknights/devigation/configuration/SecurityConfiguration.java
  src/main/java/com/darknights/devigation/security/command/application/service/RestAuthenticationEntryPoint.java
  src/test/java/com/darknights/devigation/common/advice/AuthControllerAdviceTest.java
Labels: 📬 API, ✨ Feature, 🏗️ Refactoring, ⚙ Setting, ✅ Test

#67 [#58] Feat : AuthControllerAdvice를 통해 통합 에러 처리
  src/main/java/com/darknights/devigation/common/advice/AuthControllerAdvice.java
  src/main/java/com/darknights/devigation/common/entity/error/ErrorResponse.java
  src/main/java/com/darknights/devigation/common/exception/BadRequestException.java
  src/main/java/com/darknights/devigation/common/exception/ResourceNotFoundException.java
  src/main/java/com/darknights/devigation/common/exception/UrlNullPointException.java
  src/main/java/com/darknights/devigation/common/exception/UserNotFoundException.java
  src/main/java/com/darknights/devigation/common/filter/NullPointExceptionFilter.java
  src/main/java/com/darknights/devigation/common/filter/TokenAuthenticationFilter.java
  src/main/java/com/darknights/devigation/common/handler/CustomOAuth2SuccessHandler.java
  src/main/java/com/darknights/devigation/configuration/SecurityConfiguration.java
  src/main/java/com/darknights/devigation/configuration/WebMvcConfiguration.java
  src/main/java/com/darknights/devigation/member/command/domain/aggregate/entity/enumType/Role.java
  src/main/java/com/darknights/devigation/security/command/application/controller/AuthController.java
  src/main/java/com/darknights/devigation/security/command/application/service/CustomOAuth2UserService.java
  src/main/java/com/darknights/devigation/security/command/application/service/IssueTokenService.java
  src/main/java/com/darknights/devigation/security/command/domain/exception/ResourceNotFoundException.java
  src/main/java/com/darknights/devigation/security/command/domain/exception/TokenNotFoundException.java
  src/main/java/com/darknights/devigation/security/token/UserPrincipal.java
  src/test/java/com/darknights/devigation/common/filter/TokenAuthenticationFilterTest.java
Labels: 📬 API, 🐞 BugFix, ✨ Feature, 🏗️ Refactoring

#63 [Closes #61] Feat : Roadmap Category의 entity 수정
  src/main/java/com/darknights/devigation/roadmap/command/application/dto/CreateRoadmapCategoryDTO.java
  src/main/java/com/darknights/devigation/roadmap/command/application/dto/SaveEdgeDTO.java
  src/main/java/com/darknights/devigation/roadmap/command/application/dto/SaveNodeDTO.java
  src/main/java/com/darknights/devigation/roadmap/command/application/service/CreateRoadmapCategoryService.java
  src/main/java/com/darknights/devigation/roadmap/command/application/service/DeleteRoadmapCategoryService.java
  src/main/java/com/darknights/devigation/roadmap/command/application/service/UpdateRoadmapCategoryService.java
  src/main/java/com/darknights/devigation/roadmap/command/application/service/UpdateRoadmapService.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/RoadmapRepository/RoadmapCategoryRepository.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/RoadmapRepository/RoadmapEdgeRepository.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/RoadmapRepository/RoadmapNodeRepository.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/entity/RoadmapCategory.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/entity/RoadmapEdge.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/entity/RoadmapNode.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/vo/SourceCategoryVO.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/vo/TargetCategoryVO.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/service/RoadmapCategoryService.java
  src/test/java/com/darknights/devigation/roadmap/repository/RoadmapCategoryRepositoryTests.java
  src/test/java/com/darknights/devigation/roadmap/service/RoadmapCategoryServiceTests.java
Labels: ✨ Feature, 🏗️ Refactoring

#74 [Closes #71], [Closes #73] Feat : Roadmap Category controller에서 post 요청 처리, json parsing
  build.gradle
  src/main/java/com/darknights/devigation/roadmap/command/application/controller/RoadmapCategoryController.java
  src/main/java/com/darknights/devigation/roadmap/command/application/dto/CreateEdgeDTO.java
  src/main/java/com/darknights/devigation/roadmap/command/application/dto/CreateNodeDTO.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/service/RoadmapCategoryService.java
Labels: ✨ Feature

#72 [Closes #68, Closes #69] Test : AuthControllerAdvice에 대한 통합 테스트 진행
  .github/workflows/gradle-publish.yml
  build.gradle
  src/main/java/com/darknights/devigation/common/advice/AuthControllerAdvice.java
  src/main/java/com/darknights/devigation/common/entity/api/ApiResponse.java
  src/main/java/com/darknights/devigation/common/filter/AuthenticationExceptionFilter.java
  src/main/java/com/darknights/devigation/configuration/JacksonConfiguration.java
  src/main/java/com/darknights/devigation/configuration/SecurityConfiguration.java
  src/main/java/com/darknights/devigation/member/command/domain/repository/MemberRepository.java
  src/main/java/com/darknights/devigation/member/query/domain/aggregate/entity/enumType/Role.java
  src/test/java/com/darknights/devigation/common/advice/AuthControllerAdviceIntegrationTest.java
  src/test/java/com/darknights/devigation/common/advice/AuthControllerAdviceUnitTest.java
  src/test/java/com/darknights/devigation/common/advice/SecurityAdviceIntegrationTest.java
  src/test/java/com/darknights/devigation/common/filter/NullPointExceptionFilterTest.java
Labels: 🏗️ Refactoring, ✅ Test

#78 [Closes #58] Refactor : ExceptionAssert 클래스 생성 및 리펙토링 완료
  .gitignore
  src/main/java/com/darknights/devigation/common/exception/InvalidParameterException.java
  src/main/java/com/darknights/devigation/common/exception/assertion/ExceptionAssert.java
  src/main/java/com/darknights/devigation/member/query/application/service/FindMemberService.java
  src/test/java/com/darknights/devigation/common/advice/AuthControllerAdviceIntegrationTest.java
Labels: 🏗️ Refactoring

#79 [Closes #66]Feat : Roadmap Category update 기능 작성,Test : Roadmap Category delete, update 기능 test 작성
  src/main/java/com/darknights/devigation/roadmap/command/application/service/DeleteRoadmapCategoryService.java
  src/main/java/com/darknights/devigation/roadmap/command/application/service/UpdateRoadmapCategoryService.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/RoadmapRepository/RoadmapEdgeRepository.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/RoadmapRepository/RoadmapNodeRepository.java
  src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/entity/RoadmapNode.java
  src/test/java/com/darknights/devigation/roadmap/service/RoadmapCategoryServiceTests.java
Labels: ✨ Feature, 🏗️ Refactoring, ✅ Test

#81 [closes #80] 업로드 중 사진 이외에 파일 예외처리
  src/main/java/com/darknights/devigation/aws/command/application/service/AwsS3Service.java
Labels: 🏗️ Refactoring, ✅ Test

#83 [closes #82] Content 최대값 수정
  src/main/java/com/darknights/devigation/post/command/domain/aggregate/entity/Post.java
Labels: 🏗️ Refactoring
